### ISSUE TITLE
ace样式加载不了

### ISSUE THREAD

**Issue by RQAccount** [vankop/jsoneditor-react#14]
import React from 'react';
import importedComponent from 'react-imported-component';

export const JsonEditor = importedComponent(() => Promise.all([
    import(/* webpackChunkName:'jsoneditor' */'jsoneditor-react'),
    import(/* webpackChunkName:'jsoneditor' */'brace'),
    import(/* webpackChunkName:'jsoneditor' */'brace/mode/json'),
    import(/* webpackChunkName:'jsoneditor' */'brace/theme/solarized_dark'),
]).then(([{ JsonEditor: Editor }, ace]) => {
    console.log('ace');
    return function EditorHoc(props) {
        return (
            <Editor
                ace={ace}
                theme="ace/theme/solarized_dark"
                {...props}
            />
        );
    };
}));

页面渲染后
![image](https://user-images.githubusercontent.com/20714911/62100399-2e33ed80-b2c4-11e9-842a-1717c9bfba61.png)

**Comment by vankop** [comment]
Hi! Looks like you forgot to import css as well. Try:
```
export const JsonEditor = importedComponent(() => Promise.all([
import(/* webpackChunkName:'jsoneditor' /'jsoneditor-react'),
import(/ webpackChunkName:'jsoneditor' /'brace'),
import(/ webpackChunkName:'jsoneditor' /'brace/mode/json'),
import(/ webpackChunkName:'jsoneditor' */'brace/theme/solarized_dark')
import(/ webpackChunkName:'jsoneditor' */'jsoneditor-react/es/editor.min.css'),
]).then(([{ JsonEditor: Editor }, ace]) ...
```

**Comment by RQAccount** [comment]
thanks
