### ISSUE TITLE
Webpack loaders needed

### ISSUE THREAD

**Issue by TMiguelT** [vankop/jsoneditor-react#16]
The documentation doesn't make this clear, but in order to use the `<JsonEditor>` component, you need to first:

```bash
npm install --save-dev url-loader style-loader css-loader
```

Then add to your `webpack.config.js`:
```js
    module: {
        rules: [
            {
                test: /\.css$/i,
                use: ['style-loader', 'css-loader'],
            },
            {
                test: /\.svg$/,
                use: ['url-loader']
            }
        ]
    }
```

You probably need the Babel loader too, but since most people using React have that anyway, it's less essential to point out.

I think it would be helpful if this were explained in the README.

**Comment by vankop** [comment]
You are right. I will label this as "help wanted". PRs wellcome 👍

**Comment by TMiguelT** [comment]
Hmm, except my understanding was that modules published on npm were supposed to be pre-compiled, ie having only simple (ES5) source files as their `main` entrypoint. Which is why it's not normally needed to require users to edit their webpack config.

Is there any reason why this can't be pre-compiled?

**Comment by TreTuna** [comment]
You are correct @TMiguelT with a caveat. NPM packages will normally come with multiple compilations of the code. CommonJS, AMD, UMD, ES Modules, etc... It looks like this library is getting compiled to both UMD and ES Modules, but we are currently only marking the ES Module for consumption in `package.json`. In many libraries, you will see the `main` set to the UMD version and the `module` set to the ES Module, here we have both set to `es`. If you want to use the compiled and minified version, you should pull in the `/dist/jsoneditor-react.min.js` file.

However, looking at the Webpack loaders you are adding, those are for CSS and SVG. The JS being ES6 or ES5, or whatever should have no effect on needing those loaders.

**Comment by TMiguelT** [comment]
The CSS and SVG loaders are required here, because this module directly imports CSS from JavaScript, which is obviously not going to work without a loader: https://github.com/vankop/jsoneditor-react/blob/0d805ce83862f1c562b3afde841f399dd97c473d/src/Editor.jsx#L4-L5

**Comment by vankop** [comment]
added info in readme

**Comment by kushagra010** [comment]
@vankop @multimeric I use tsup, is there any alterative for that ? 
I tried the following, but no luck.
```
export default defineConfig({
  esbuildPlugins: [cssModulesPlugin(), svgrPlugin({ exportType: 'named' })],
  entry: {
    index: 'src/index.ts',
    vectors: 'src/assets/vectors/index.ts'
  },
  sourcemap: true,
  clean: true,
  outDir: 'dist',
  bundle: true,
  splitting: true,
  dts: true,
  target: 'es6',
  platform: 'browser',
  format: 'cjs',
  loader: {
    '.css': 'css'     <------------
  }
});
```
