### ISSUE TITLE
Remove use of componentWillReceiveProps

### ISSUE THREAD

**Issue by kylethorpe** [vankop/jsoneditor-react#20]
Due to componentWillReceiveProps being [not recommended for use](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html), this code should be refactored to use componentDidUpdate.

**Comment by vankop** [comment]
@kylethorpe Thanks for pointing this, you are totally right! Marking this as `help wanted`. PRs always welcome 🤗
