### ISSUE TITLE
[request] Update npm version 

### ISSUE THREAD

**Issue by Far3t** [vankop/jsoneditor-react#23]
Hello,

When using your package, I saw that it builds its own jsoneditor.
But the interface of it has changed in the current month (added for example the onValidationError props).
Is this possible to re-push an update of your package on npm?

**Comment by vankop** [comment]
PRs always welcome!

**Comment by Far3t** [comment]
Can't PR an update on a npm package :-(.
The only thing I can do is fork yours, build and publish another package onto npm (which is not very nice but...)

**Comment by vankop** [comment]
> But the interface of it has changed in the current month (added for example the onValidationError props).

As I understand you want to support this parameters in this package? or you want update `peerDependency` ?

**Comment by Far3t** [comment]
The thing is, everytime you'll launch rollup, it will take the jsoneditor you have on your node_modules because of:
https://github.com/vankop/jsoneditor-react/blob/master/src/Editor.jsx#L3
(Dunno if one can exclude that with rollup, don't know it very well).
So, even if your peerDependencies specify ^7.1, the package you will build and publish onto npm will have the jsoneditor-minimalistic built into it. So, even if jsoneditor goes to version 7.8 and I install it, your React wrapper will only take the jsoneditor-minimalistic build into it (Or I misunderstood something).

If you do want to keep the minimalistic one, not sure if we can exclude it with rollup.
If you don't want to have a jsoneditor built into your package, try import it directly.
Not sure about what you want for your package, but now, it will only have the jsoneditor when you build it.

**Comment by vankop** [comment]
Fixed in https://github.com/vankop/jsoneditor-react/commit/b0899054c39bfcd5237ca93a3d299cf80e8838fe

**Comment by vankop** [comment]
published in `3.0.0` version
