### ISSUE TITLE
expandAll usage

### ISSUE THREAD

**Issue by jamessergeant** [vankop/jsoneditor-react#26]
Sorry, I'm not sure where else to ask this. I'm just having difficulty trying to figure out how to call expandAll / collapseAll on the component. Any advice would be appreciated.

**Comment by jamessergeant** [comment]
Actually I guess more accurately I am after having the editor be expanded at all times. I've been able to access the expandAll function on the jsonEditor instance however on a change the field loses focus.

**Comment by jamessergeant** [comment]
I've managed a hacky work around for this. Will close out but if anyone has advice, would love to hear it.

**Comment by vankop** [comment]
Hi! sorry fo delay, you need to get json editor instance using `ref` on component, so after that you can call any supported methods
