### ISSUE TITLE
Sort level 0 JSON attributes on jsoneditor-react component is loaded

### ISSUE THREAD

**Issue by fhperuchi** [vankop/jsoneditor-react#31]
Hi!

How do I to sort level 0 JSON attributes after component is loaded?

Thanks.

**Comment by italoayres** [comment]
You can use the undocumented property sortObjectKeys={true} for this. Just made a [PR](https://github.com/vankop/jsoneditor-react/pull/38) to add it to the props definition, but you should have no problem using it anyway.

```
<Editor
    value={value}
    onChange={this.handleChange}
    sortObjectKeys={true}
/>
```
