### ISSUE TITLE
[request] re-publish on npm

### ISSUE THREAD

**Issue by meneman** [vankop/jsoneditor-react#8]
Hi vankop,

When installing your package via npm, it comes with its own copy of josdejong/jsoneditor. Since your last publish on npm is 8 month ago, it lacks cool new features from josdejong/jsoneditor. ( even so your package is compatible with them)

At the moment, one has to to build jsoneditor-react from source (or maybe npm install from github-link) in order to have it use a newer build of josdejong/jsoneditor.

**Comment by vankop** [comment]
@meneman I decided to publish `1.0.0` version with jsoneditor as `peerDependency` so if you want to install latest versions run:
```
npm install --save jsoneditor jsoneditor-react
```
and it doesn't affects users with version less than `1.0.0` due to semver policy.
