### ISSUE TITLE
Missing css when using nginx to serve it

### ISSUE THREAD

**Issue by can-007** [vankop/jsoneditor-react#83]
when I use `yarn start`, it looks fine:
<img width="523" alt="Screen Shot 2022-04-26 at 23 42 54" src="https://user-images.githubusercontent.com/56532901/165339589-bb5508fa-9c01-4c49-834e-50132192ce6e.png">

when I use yarn build and config nginx to serve it, it looks wrong:
<img width="242" alt="Screen Shot 2022-04-26 at 23 44 18" src="https://user-images.githubusercontent.com/56532901/165339853-adff4c12-bb03-4d8b-86c3-bbc5c6da66e0.png">

The nginx.conf is:
```
http {

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    sendfile        on;

    keepalive_timeout  65;

    gzip  on;

    server {
        listen       3000;

        location / {
            #root   /usr/share/nginx/html;
            root   /....../build;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        location /stories {
            set         $args   $args;
            proxy_pass  http://localhost:8000;
        }
    }
}
```

Could you help make `nginx` version work like `yarn start `version?
Thanks.

**Comment by vankop** [comment]
I can't help you for setting up your webserver..
