### ISSUE TITLE
Clicking the nav items throws an error

### ISSUE THREAD

**Issue by shanedaugherty** [vankop/jsoneditor-react#9]
When clicking these:
https://www.dropbox.com/s/wjn1w3n0ec48u7h/Screenshot%202018-12-28%2011.49.23.png?dl=0

This happens:
https://www.dropbox.com/s/2f2rae0cua28edr/Screenshot%202018-12-28%2011.50.04.png?dl=0

Anyone else having this problem?

**Comment by vankop** [comment]
Sorry for so later answer. You need to ask this in upstream in https://github.com/josdejong/jsoneditor with minimal reproducible repo
