### ISSUE TITLE
Label 'Preview' is not associated with its edit field present under 'Transform' dialog box.

### ISSUE THREAD

**Issue by msftedad** [vankop/jsoneditor-react#99]
**Test Environment**
OS Version: Windows 11 Version 22H2 (OS Build 23619.1000)
Browser: Edge Version 121.0.2277.83  (Official build) (64-bit)

**Repro steps**
1.Open URL - [jsoneditor-example - CodeSandbox](https://codesandbox.io/p/sandbox/jsoneditor-example-kfdp6f?2.file=%2fpackage.json:11%2c33)
3.Navigate to 'Filter' button in the code editor and activate it.
4.Transform dialog will get open.
5.Navigate to 'Preview' edit field and observe the issue.

**Actual Result**
Label 'Preview' is not associated with its edit field present under 'Transform' dialog box.

**Expected Result**
Label 'Preview' should be associated with its edit field present under 'Transform' dialog box.

**Attachment**
https://github.com/vankop/jsoneditor-react/assets/93735775/1bac3bf7-aac1-44ab-bc2b-833480361f65

**Comment by msftedad** [comment]
Hi team, Any update on this issue?

**Comment by vankop** [comment]
hi, you need to address this issue to jsoneditor itself https://github.com/josdejong/jsoneditor

this is only react wrapper on top of it.
